version: '3.8'
services:
  postgresql:
    image: postgres:17.0
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${db_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static:/app/staticfiles
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      postgresql:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/static
    ports:
      - "8000:80"
    depends_on:
      - django
volumes:
  static:
  postgresql-db: