# Generated by Django 5.1.2 on 2024-10-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_meals_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='mealId',
        ),
        migrations.AlterField(
            model_name='meals',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
