"""empty message

Revision ID: 77bec6bfafce
Revises: 3ff294ebf8b1
Create Date: 2024-10-12 23:09:36.472531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bec6bfafce'
down_revision = '3ff294ebf8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
