"""empty message

Revision ID: f12932775ab6
Revises: e6aa3d9059de
Create Date: 2024-10-15 06:26:06.052470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12932775ab6'
down_revision = 'e6aa3d9059de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_meal_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_constraint('uq_meal_name', type_='unique')

    # ### end Alembic commands ###
